# Generated by Django 5.1.5 on 2025-02-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42, unique=True),
        ),
    ]
