# Generated by Django 5.1.5 on 2025-02-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_vip_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
